name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - run: yarn install

      - run: yarn build

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          # dist リポジトリのアップロード
          path: './dist'

      - uses: actions/deploy-pages@v1
